# Generated by Django 4.2 on 2024-08-28 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='texto',
        ),
    ]
