# Generated by Django 4.2 on 2024-08-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0002_remove_mensaje_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='texto',
            field=models.TextField(default='hola'),
        ),
    ]
